name: jtest-jsdoc

on: workflow_dispatch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

    - name: LsBeforeCheckout
      run: |
        pwd
        ls -la
      
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: LsAfterCheckout
      run: |
        pwd
        ls -la
      
    - name: Mkdir
      run: mkdir documentation
      
    - name: NpmInstall
      run: npm install -g jsdoc
      
    - name: Cat
      run: cat package.json
      
    - name: GenerateJsDoc
      run: npm run doc
      
#    - name: Build
#      uses: jurajvarga/jtest-docz2@master
#      with: 
#        source_dir: /
#        output_dir: /
#        config_file: jsdoc.json
#        recurse: true
#        template: minami
#        front_page: README.md
        
#    - name: Deploy
#      uses: jurajvarga/jtest-docz2@master
#      with:
#        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        publish_dir: ./out
