name: jtest-jsdoc

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: HelloWorld
      run: echo "Hello World!" 
      
    - name: Pwd
      run: pwd
      
    - name: Ls
      run: ls -la
      
    - name: Build
      uses: jurajvarga/jtest-docz2@master
      with: 
        source_dir: /src
        output_dir: /out
        config_file: jsdoc.json
        recurse: true
        template: minami
        front_page: README.md
        
    - name: Deploy
      uses: jurajvarga/jtest-docz2@master
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./out
