name: jtest-jsdoc
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: my-step
      run: echo "Hello World!" 
    - name: Build
      uses: jurajvarga/jtest-docz2@v1
      with: 
        source_dir: ./src
        recurse: true
        output_dir: ./out
