name: jtest-jsdoc

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Mkdir
      run: mkdir documentation
      
    - name: NpmInstall
      run: npm install -g jsdoc
      
    - name: GenerateJsDoc
      run: npm run doc
      
#    - name: Build
#      uses: jurajvarga/jtest-docz2@master
#      with: 
#        source_dir: /
#        output_dir: /
#        config_file: jsdoc.json
#        recurse: true
#        template: minami
#        front_page: README.md
        
#    - name: Deploy
#      uses: jurajvarga/jtest-docz2@master
#      with:
#        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        publish_dir: ./out
