name: jtest-jsdoc

on: workflow_dispatch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository jtest_docz
      uses: actions/checkout@v2.3.4

    - name: NpmInstall jsdoc
      run: npm install -g jsdoc
      
    - name: Generate jsdoc
      run: npm run doc
      
#-----------------------      
    - name: Push Documentation into the gh-pages branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: Automated Change
         push_options: '--force'
         branch: gh-pages
         create_branch: true
         file_pattern: 'docs-output/**'
#------------------------

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs-output
