name: jtest-jsdoc

on: workflow_dispatch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Repository jtest_docz
      uses: actions/checkout@v2.3.4

    - name: NpmInstall jsdoc
      run: npm install -g jsdoc
      
    - name: Generate jsdoc
      run: npm run doc


#  copy:
#    name: Copy my folder
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#    - name: copy
#      env:
#          SRC_FOLDER_PATH: 'docs-output/**'
#          TARGET_BRANCH: 'gh-pages'
#      run: |
#          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
#          git config --global user.name 'GitHub Action'
#          git config --global user.email 'action@github.com'
#          git fetch                         # fetch branches
#          git checkout $TARGET_BRANCH       # checkout to your branch
#          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
#          git add -A
#          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
#          git push origin $TARGET_BRANCH # push to remote branch

#-----------------------      
    - name: Push Documentation into the gh-pages branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: Automated Change
         push_options: '--force'
         branch: gh-pages
         create_branch: true
         file_pattern: 'docs/**'
#------------------------

#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        publish_dir: ./docs
